server:
  port: 8181

spring:
  application:
    name: planning
  data:
    mongodb:
      uri: mongodb+srv://kouskefil:Mo%4011109010%23@cluster0.coruxqx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: planning
  jmx:
    enabled: false