server:
  port: 8080
spring:
  application:
    name: employee
  data:
    mongodb:
      uri: ${DB_URI}
      database: ${DB_NAME}
  jmx:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka