server:
  port: 8080

spring:
  application:
    name: employee
  data:
    mongodb:
      uri: mongodb+srv://kouskefil:Mo%4011109010%23@cluster0.coruxqx.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: users
  jmx:
    enabled: false